//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCMS_APIServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproverStack
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public string RefNo { get; set; }
        public string Designation { get; set; }
        public int OrderNo { get; set; }
        public string Status { get; set; }
        public string RoleCode { get; set; }
        public bool Removable { get; set; }
    }
}
