//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCMS_APIServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string NotifMsg { get; set; }
        public string Category { get; set; }
        public string ReadStatus { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedTime { get; set; }
    }
}
